### ISSUE TITLE
Invalid characters in SmartThings devices stops discovery

### ISSUE THREAD

**Issue by Mustavio** [BobRak/OpenHAB-Smartthings#16]
I had some Things with invalid characters. This stopped discovery and additional devices did not show in Inbox. (So I would see some but not all things). Renaming the things in SmartThings fixed the issue.

```
2017-12-21 12:31:56.949 [INFO ] [hings.internal.SmartthingsHttpClient] - Sent message "{"discovery": "yes"}" with path "/discovery" to the Smartthings hub, recieved HTTP status 202
2017-12-21 12:31:57.383 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'smartthings:battery:c63cedcc:WaterLeakSensorBasement' to inbox.
2017-12-21 12:31:57.393 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'smartthings:battery:c63cedcc:WaterLeakSensorMasterBath' to inbox.
2017-12-21 12:31:57.394 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=org/openhab/binding/smartthings/discovery] {data=["{\"capability\": \"battery\", \"attribute\": \"battery\", \"name\": \"Water Leak Sensor Basement\", \"id\": \"4fffc491-4f4f-461c-b440-4051b593b6ef\" }","{\"capability\": \"battery\", \"attribute\": \"battery\", \"name\": \"Water Leak Sensor Master Bath\", \"id\": \"e13a4bb2-c4c8-4e8e-bd85-5467af8714f8\" }","{\"capability\": \"presenceSensor\", \"attribute\": \"presence\", \"name\": \"XXXXX's Android\", \"id\": \"8535a414-4600-41bd-bbec-d94e8d30a40d\" }","{\"capability\": \"temperatureMeasurement\", \"attribute\": \"temperature\", \"name\": \"Water Leak Sensor Master Bath\", \"id\": \"e13a4bb2-c4c8-4e8e-bd85-5467af8714f8\" }","{\"capability\": \"temperatureMeasurement\", \"attribute\": \"temperature\", \"name\": \"Water Leak Sensor Basement\", \"id\": \"4fffc491-4f4f-461c-b440-4051b593b6ef\" }","{\"capability\": \"waterSensor\", \"attribute\": \"water\", \"name\": \"Water Leak Sensor Basement\", \"id\": \"4fffc491-4f4f-461c-b440-4051b593b6ef\" }","{\"capability\": \"waterSensor\", \"attribute\": \"water\", \"name\": \"Water Leak Sensor Master Bath\", \"id\": \"e13a4bb2-c4c8-4e8e-bd85-5467af8714f8\" }"]} | {org.osgi.service.event.EventHandler}={event.topics=org/openhab/binding/smartthings/discovery, service.id=319, service.bundleid=206, service.scope=singleton} | Bundle(org.openhab.binding.smartthings_2.2.0.201712120439 [206])]
java.lang.IllegalArgumentException: UID segment 'XXXXXXXX'sAndroid' contains invalid characters. Each segment of the UID must match the pattern [A-Za-z0-9_-]*.
	at org.eclipse.smarthome.core.thing.UID.validateSegment(UID.java:96) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:74) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:144) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.openhab.binding.smartthings.discovery.SmartthingsDiscoveryService.createDevice(SmartthingsDiscoveryService.java:190) [206:org.openhab.binding.smartthings:2.2.0.201712120439]
	at org.openhab.binding.smartthings.discovery.SmartthingsDiscoveryService.handleEvent(SmartthingsDiscoveryService.java:167) [206:org.openhab.binding.smartthings:2.2.0.201712120439]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
	at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
	at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by BobRak** [comment]
@Mustavio Thanks for letting me know you discovered the problem. I'll keep that in mind incase someone else reports a similar problem.
