### ISSUE TITLE
Exception on shutdown?

### ISSUE THREAD

**Issue by megaoldgeek** [BobRak/OpenHAB-Smartthings#30]
Running it thru the paces...

2018-01-15 21:44:19.920 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: {}
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:105) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135) ~[?:?]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:361) ~[?:?]
	at org.eclipse.jetty.client.PoolingHttpDestination.close(PoolingHttpDestination.java:240) ~[?:?]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:248) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.stopHttpClient(SmartthingsHttpClient.java:79) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsBridgeHandler.dispose(SmartthingsBridgeHandler.java:68) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	... 3 more
2018-01-15 21:44:19.926 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: {}
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:105) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135) ~[?:?]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:361) ~[?:?]
	at org.eclipse.jetty.client.PoolingHttpDestination.close(PoolingHttpDestination.java:240) ~[?:?]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:248) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.stopHttpClient(SmartthingsHttpClient.java:79) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsBridgeHandler.dispose(SmartthingsBridgeHandler.java:68) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	... 3 more
2018-01-15 21:44:19.924 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: {}
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:105) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135) ~[?:?]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:361) ~[?:?]
	at org.eclipse.jetty.client.PoolingHttpDestination.close(PoolingHttpDestination.java:240) ~[?:?]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:248) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.stopHttpClient(SmartthingsHttpClient.java:79) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsBridgeHandler.dispose(SmartthingsBridgeHandler.java:68) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	... 3 more
2018-01-15 21:44:19.923 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: {}
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:105) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135) ~[?:?]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:361) ~[?:?]
	at org.eclipse.jetty.client.PoolingHttpDestination.close(PoolingHttpDestination.java:240) ~[?:?]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:248) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.stopHttpClient(SmartthingsHttpClient.java:79) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsBridgeHandler.dispose(SmartthingsBridgeHandler.java:68) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	... 3 more
2018-01-15 21:44:19.921 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: {}
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:105) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135) ~[?:?]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:361) ~[?:?]
	at org.eclipse.jetty.client.PoolingHttpDestination.close(PoolingHttpDestination.java:240) ~[?:?]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:248) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[?:?]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.stopHttpClient(SmartthingsHttpClient.java:79) ~[?:?]
	at org.openhab.binding.smartthings.handler.SmartthingsBridgeHandler.dispose(SmartthingsBridgeHandler.java:68) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	... 3 more

**Comment by megaoldgeek** [comment]
This is benign... only seen it once.. probably triggered by my mass stop/starts.
