### ISSUE TITLE
although the handler was already disposed.

### ISSUE THREAD

**Issue by edwolfe3** [BobRak/OpenHAB-Smartthings#93]
What does this mean and what should I look at to troubleshoot?

`2020-06-20 22:27:59.177 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler SmartthingsThingHandler of thing smartthings:switchLevel:House:OfficeEdsDeskLight tried updating channel switch although the handler was already disposed.`

**Comment by edwolfe3** [comment]
FYI: I'm also getting a lot of the following; not sure if it is related or not:

```
2020-06-20 22:30:06.009 [INFO ] [rnal.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with exception

java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed

	at org.eclipse.jetty.client.HttpDestination$TimeoutTask.onTimeoutExpired(HttpDestination.java:529) ~[?:?]

	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_252]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by BobRak** [comment]
I just deployed a new jar. Are you still having the ```
Attempt to send command to the Smartthings hub failed with exception java.util.concurrent.TimeoutException``` If so I have something else you might try.  

Also, read about clearing the cache.
